CREATE TABLE IF NOT EXISTS tasks (
    -- UUID values are generated by the application before inserts reach PostgreSQL.
    id UUID PRIMARY KEY,

    -- The title constraint protects against empty or whitespace-only titles.
    title TEXT NOT NULL,

    description TEXT,

    -- The status constraint protects the allowed task lifecycle values.
    status TEXT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    -- deleted_at supports soft delete without removing historical rows immediately.
    deleted_at TIMESTAMPTZ,

    CONSTRAINT tasks_title_not_blank CHECK (length(trim(title)) > 0),
    CONSTRAINT tasks_status_valid CHECK (status IN ('pending', 'in_progress', 'done'))
);

-- The partial index supports active task listing ordered by newest records first.
CREATE INDEX IF NOT EXISTS idx_tasks_active_created_at
    ON tasks (created_at DESC)
    WHERE deleted_at IS NULL;
